# Generated by Django 5.2 on 2025-04-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('is_gif', models.BooleanField(default=False)),
                ('is_sticker', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='general', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_memes/')),
                ('top_text', models.CharField(blank=True, max_length=200, null=True)),
                ('bottom_text', models.CharField(blank=True, max_length=200, null=True)),
                ('font', models.CharField(default='Impact', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.memetemplate')),
            ],
        ),
    ]
