# Generated by Django 5.2 on 2025-08-03 20:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=100)),
                ('duration', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='memetemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usermeme',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermeme',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermeme',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usermeme',
            name='template_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usermeme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='category',
            field=models.CharField(db_index=True, default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='is_gif',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='is_sticker',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usermeme',
            name='bottom_text',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermeme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usermeme',
            name='font',
            field=models.CharField(db_index=True, default='Impact', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermeme',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermeme',
            name='image',
            field=models.ImageField(upload_to='user_memes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='usermeme',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_memes', to='app1.memetemplate'),
        ),
        migrations.AlterField(
            model_name='usermeme',
            name='top_text',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='memetemplate',
            index=models.Index(fields=['category', 'is_gif'], name='app1_memete_categor_11e9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='memetemplate',
            index=models.Index(fields=['name'], name='app1_memete_name_0b6841_idx'),
        ),
        migrations.AddIndex(
            model_name='memetemplate',
            index=models.Index(fields=['created_at'], name='app1_memete_created_1f574a_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeme',
            index=models.Index(fields=['created_at'], name='app1_userme_created_b0284e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeme',
            index=models.Index(fields=['template'], name='app1_userme_templat_7759ab_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeme',
            index=models.Index(fields=['top_text', 'bottom_text'], name='app1_userme_top_tex_81195e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeme',
            index=models.Index(fields=['font'], name='app1_userme_font_b2f62f_idx'),
        ),
        migrations.AddIndex(
            model_name='performancelog',
            index=models.Index(fields=['operation', 'timestamp'], name='app1_perfor_operati_f755a6_idx'),
        ),
        migrations.AddIndex(
            model_name='performancelog',
            index=models.Index(fields=['duration'], name='app1_perfor_duratio_1c6fad_idx'),
        ),
    ]
